project:
  type: default

quarto-required: ">=1.4"

format:
  html:
    toc: true
    highlight-style: ayu
    theme:
      light: flatly
      dark:  darkly
    citation-hover: true
    footnotes-hover: true
