project:
  type: default

quarto-required: ">=1.6"

format:
  html:
    embed-resources: true
    toc: true
    highlight-style: ayu
    theme:
      light: flatly
      dark:  darkly
    citation-hover: true
    footnotes-hover: true
