---
title: "CPSC 320 worksheets survey"
author: "Stephan Koenig and Patrice Belleville"
format:
  html: default
  docx: default
---

## Preamble

Thank you for taking the time to complete this survey.
As you have discovered, worksheets are an integral part of CPSC 320.
The survey will ask you to reflect on your experience with worksheets in CPSC 320.
Your responses will help the CPSC 320 instructional team better understand your experiences in the course and consider how they can improve it in the future.
The survey should take about 5--10 minutes to complete.

## Informed consent

The primary use of these survey data is for course improvement and to explore student experiences in CPSC 320.
Your answers will **not be anonymous**.
You will log in with your CWL, the system will use that information to automatically add your name to your survey responses, and we will ask you for your student number.
The only people with access to the non-anonymized response data are Stephan Koenig, Science Education Specialist in the Computer Science department, and Patrice Belleville, Associate Professor of Teaching.
They might use the identifying information to associate your survey responses with your grades in CPSC 320.
A summary of the results without identifying information will be available to your instructors.
The summary might include statements about how final course grades correlated with responses to some survey questions.
If you have any questions or would like to learn more about this survey, please contact the survey analysts, Stephan Koenig (<stephan.koenig@ubc.ca>) or Patrice Belleville (<patrice@cs.ubc.ca>).

The instructional team may also want to include some of the data for conference presentations and/or publications in the future, but only data from students who consent to their use would be included in this analysis.
The use of your survey responses is entirely voluntary and you may refuse their use for external analysis at any time without jeopardy to your class standing.
Either way, by filling out this survey, you will get an extra x% on your assignment grade at the end of the course.
**You must complete the entire survey to be awarded the bonus.** Would you be willing to have your data included in such external analyses?

-   [ ] Yes, my data can be considered for conference presentations and/or publications
-   [ ] No, only use my data for internal course improvement

Questions:

> Question 1 and 2 might be redundant if we ask them to login using their CWL.

1.  Name

2.  Student number

> Questions 3 to 5 copied from an earlier survey (2018W) that asked about all of the course activities, not only the worksheets.
> Our SIGCSE 2020 paper concentrated on the tutorial quizzes, and didn't look at the data about worksheets.
> I believe we need to ask these questions here as the answers are likely to be correlated to those of questions 6 to 9.

3.  Please rate your agreement or disagreement with the following statements:

    > To keep the survey to a reasonable length, I would recommend keeping only 3a, 3b and 3f.

    a.  The in-lecture worksheet activities were engaging.

        ```         
        * Strongly Disagree * Disagree * Neutral * Agree * Strongly Agree
        ```

    b.  The in-lecture worksheet activities were useful for learning the course concepts

        ```         
        * Strongly Disagree * Disagree * Neutral * Agree * Strongly Agree
        ```

    c.  The in-lecture worksheet activities were useful for completing the assignments

        ```         
        * Strongly Disagree * Disagree * Neutral * Agree * Strongly Agree
        ```

    d.  The in-lecture worksheet activities were useful for preparing for the exams

        ```         
        * Strongly Disagree * Disagree * Neutral * Agree * Strongly Agree
        ```

    e.  The in-lecture worksheet activities were useful for understanding the pre-class readings

        ```         
        * Strongly Disagree * Disagree * Neutral * Agree * Strongly Agree
        ```

    f.  The in-lecture worksheet activities were useful for your overall success in the course

        ```         
        * Strongly Disagree * Disagree * Neutral * Agree * Strongly Agree
        ```

4.  How often did you attend lectures?
    (either your scheduled lecture or another timeslot)?

    ```         
    * Never or rarely * Sometimes * Half the time * Frequently * Always or almost always
    ```

5.  To what extent did the worksheet-based lecture style encourage or discourage your attendance at lectures?

    ```         
    * Strongly Discourage * Discourage * Neutral * Enourage * Strongly Encourage
    ```

6.  On average, what percentage of the time given in class to work in small groups on worksheet questions did you spend doing each of the following?
    Note that talking about a question with other members of your group counts as working on the worksheet.

    a.  Working on the worksheet and making (some) progress?

    b.  Working on the worksheet but getting stuck and not making any or much progress?

    c.  Working ahead or waiting for the instructor to go over solutions after you'd completed the part(s) of the worksheet that had been assigned?

    d.  Waiting for the instructor to go over solutions, without having first completed the part(s) of the worksheet that had been assigned?

    e.  Something else?

        Write down what that something else was here: \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_

7.  If your answer to question 3d was 33% \[figure out right %age\] or higher, please explain why you waited for the instructor to go over solutions without having first completed the part(s) of the worksheet that had been assigned.

8.  Did the percentages from question 3

    a.  Remain similar for every worksheet?

    b.  Vary wildly from one worksheet to another, or from one part of one worksheet to the next?

9.  If your answer to question 5 was (a), then you're done and only need to click Submit.
    If your answer to question 5 was (b), why did the percentages from question 3 vary?

    a.  It depends on the difficulty of the questions

    b.  It depends on my physical and mental state at the time.

    c.  I sometimes used the time reserved for group work to complete work for another course instead.

    d.  Some other reason

        Write down what that other reason was here: \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_
